---

- name: Copy banner files
  ansible.builtin.template:
    src: "{{ banner_prefix }}/{{ template }}"
    dest: "{{ file }}"
    owner: root
    group: root
    mode: 0644
  loop: "{{ files }}"
  loop_control:
    loop_var: file
