---
# tasks file for hudecof.banners

- name: copy ISSUE files
  include: common-copy.yml files={{ banner_issue_files }} template={{ banner_issue_template }}
  when: banner_issue
  tags:
    - banners
    - banners:issue

- name: copy MOTD files
  include: common-copy.yml files={{ banner_motd_files }} template={{ banner_motd_template }}
  when: banner_motd
  tags:
    - banners
    - banners:motd
